### ISSUE TITLE
Full file system read/write access is considered potentially unsafe

### ISSUE THREAD

**Issue by amolenaar** [flathub/org.gaphor.Gaphor#91]
Flathub.org states that our app is potentially unsafe:

<img width="1426" alt="Screenshot 2023-12-01 at 13 47 10" src="https://github.com/flathub/org.gaphor.Gaphor/assets/96249/81843501-37d7-4033-8a91-19e93ac003d2">

Should we limit access to the home directory only?

@danyeaw What do you think?

**Comment by danyeaw** [comment]
Hey @amolenaar, that makes sense to me. Maybe the only thing I don't know about is something like saving to a USB drive.

**Comment by amolenaar** [comment]
Hmm.. If we restrict it to the home directory, it states ["Home folder read/write access"](https://flathub.org/apps/com.endlessm.photos). Not sure if that's much better...

Gimp and Inkscape have the same "unsafe" condition listed.

**Comment by amolenaar** [comment]
If I drop the `--filesystem=host` option, I can open a model, but the path looks funny:

![image](https://github.com/flathub/org.gaphor.Gaphor/assets/96249/1ac47d2e-1c5b-4603-99f5-e25c499fc694)

**Comment by danyeaw** [comment]
Hi @amolenaar, do you mean release a flatpak of Gaphor with these changes?

**Comment by amolenaar** [comment]
Yes (or the next release), where we remove filesystem permissions from the flatpak manifest.

**Comment by danyeaw** [comment]
Got it,  I forgot we have to update the manifest in this repo as well.
